import os
import fitz
import pytesseract
from pytesseract import Output
from PIL import Image
import json
from google import genai
from google.genai import types

doc = fitz.open('/Users/dmitt/Desktop/QuantGuide_Web/a-practical-guide-to-quantitative-finance-interviews.pdf')
page = doc[50]
pix = page.get_pixmap(matrix=fitz.Matrix(2, 2))
img_path = '/tmp/page50.png'
pix.save(img_path)

img = Image.open(img_path)
data = pytesseract.image_to_data(img, output_type=Output.DICT)

words = []
for i in range(len(data['text'])):
    w = data['text'][i].strip()
    if w:
        words.append({
            'text': w,
            'left': data['left'][i],
            'top': data['top'][i],
            'width': data['width'][i],
            'height': data['height'][i]
        })

full_text = " ".join([w['text'] for w in words])

client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

schema = {
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "title": {"type": "string", "description": "Short title generated by you for the problem"},
            "topic": {"type": "string"},
            "question_start_word": {"type": "string", "description": "The exact literal first 3 words of the question text"},
            "question_end_word": {"type": "string", "description": "The exact literal last 3 words of the question text"},
            "solution_start_word": {"type": "string", "description": "The exact literal first 3 words of the solution text"},
            "solution_end_word": {"type": "string", "description": "The exact literal last 3 words of the solution text"}
        },
        "required": ["title", "topic", "question_start_word", "question_end_word", "solution_start_word", "solution_end_word"]
    }
}

response = client.models.generate_content(
    model='gemini-2.5-flash',
    contents=f"Extract all quantitative questions and solutions from this OCR text. Provide exact 3-word literal string matches for the start and end of each section.\n\nText:\n{full_text}",
    config=types.GenerateContentConfig(
        response_mime_type="application/json",
        response_schema=schema,
    ),
)
print("GEMINI JSON:")
print(response.text)
